                                        -- QUERYS CARREGAR DADOS DOS TRIMESTRES (EXECUTAR UMA POR VEZ)

-- CARREGANDO DADOS DO 1 TRIMESTRE DE 2020
LOAD DATA LOCAL INFILE 'C:/Users/Vini/Pictures/INTUITIVE_TESTS/T3_database/files/2020/1T2020.csv'
INTO TABLE DEMONSTRACOES_CONTABEIS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(@DATAS, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_FINAL)
SET DATAS = STR_TO_DATE(@DATAS, '%d/%m/%Y');

-- CARREGANDO DADOS DO 2 TRIMESTRE DE 2020
LOAD DATA LOCAL INFILE 'C:/Users/Vini/Pictures/INTUITIVE_TESTS/T3_database/files/2020/2T2020.csv'
INTO TABLE DEMONSTRACOES_CONTABEIS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(@DATAS, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_FINAL)
SET DATAS = STR_TO_DATE(@DATAS, '%d/%m/%Y');

-- CARREGANDO DADOS DO 3 TRIMESTRE DE 2020
LOAD DATA LOCAL INFILE 'C:/Users/Vini/Pictures/INTUITIVE_TESTS/T3_database/files/2020/3T2020.csv'
INTO TABLE DEMONSTRACOES_CONTABEIS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(@DATAS, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_FINAL)
SET DATAS = STR_TO_DATE(@DATAS, '%d/%m/%Y');

-- CARREGANDO DADOS DO 4 TRIMESTRE DE 2020
LOAD DATA LOCAL INFILE 'C:/Users/Vini/Pictures/INTUITIVE_TESTS/T3_database/files/2020/4T2020.csv'
INTO TABLE DEMONSTRACOES_CONTABEIS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(@DATAS, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_FINAL)
SET DATAS = STR_TO_DATE(@DATAS, '%d/%m/%Y');

-- CARREGANDO DADOS DO 1 TRIMESTRE DE 2021
LOAD DATA LOCAL INFILE 'C:/Users/Vini/Pictures/INTUITIVE_TESTS/T3_database/files/2021/1T2021.csv'
INTO TABLE DEMONSTRACOES_CONTABEIS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(@DATAS, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_FINAL)
SET DATAS = STR_TO_DATE(@DATAS, '%d/%m/%Y');

-- CARREGANDO DADOS DO 2 TRIMESTRE DE 2021
LOAD DATA LOCAL INFILE 'C:/Users/Vini/Pictures/INTUITIVE_TESTS/T3_database/files/2021/2T2021.csv'
INTO TABLE DEMONSTRACOES_CONTABEIS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(@DATAS, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_FINAL)
SET DATAS = STR_TO_DATE(@DATAS, '%d/%m/%Y');

-- CARREGANDO DADOS DO 3 TRIMESTRE DE 2021
LOAD DATA LOCAL INFILE 'C:/Users/Vini/Pictures/INTUITIVE_TESTS/T3_database/files/2021/3T2021.csv'
INTO TABLE DEMONSTRACOES_CONTABEIS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(@DATAS, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_FINAL)
SET DATAS = STR_TO_DATE(@DATAS, '%d/%m/%Y');



                                        -- QUERY CARREGAR DADOS DAS OPERADORAS
LOAD DATA LOCAL INFILE 'C:/Users/Vini/Pictures/INTUITIVE_TESTS/T3_database/files/Relatorio_cadop.csv'
INTO TABLE OPERADORAS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 3 LINES
(REG_ANS, CNPJ, RAZAO_SOCIAL, NOME_FANTASIA, MODALIDADE, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, UF, CEP, DDD, TELEFONE, FAX, ENDERECO_ELETRONICO, REPRESENTANTE, CARGO_REPRESENTANTE, DATA_REG_ANS);
