-- Quais as 10 operadoras que mais tiveram despesas com "EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR" no último trimestre
SELECT dc.ID, dc.REG_ANS, dc.CD_CONTA_CONTABIL, dc.DESCRICAO, SUM(CAST(dc.VL_SALDO_FINAL AS DECIMAL(10,2))) AS VL_SALDO
FROM DEMONSTRACOES_CONTABEIS dc
LEFT JOIN OPERADORAS o
ON dc.REG_ANS = o.REG_ANS
WHERE
  (DATAS BETWEEN '2021-01-01' AND '2021-04-01') and
  DESCRICAO = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR'
GROUP BY dc.REG_ANS ORDER BY VL_SALDO DESC
LIMIT 10


-- Quais as 10 operadoras que mais tiveram despesas com "EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR" no último ano
SELECT dc.ID, dc.REG_ANS, dc.CD_CONTA_CONTABIL, dc.DESCRICAO, SUM(CAST(dc.VL_SALDO_FINAL AS DECIMAL(10,2))) AS VL_SALDO
FROM DEMONSTRACOES_CONTABEIS dc
LEFT JOIN OPERADORAS o
ON dc.REG_ANS = o.REG_ANS
WHERE
  (DATAS BETWEEN '2021-01-01' AND '2022-01-01') and
  DESCRICAO = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR'
GROUP BY dc.REG_ANS ORDER BY VL_SALDO DESC
LIMIT 10